stages:
  pull_data:
    cmd: dvc pull
  generate_data:
    cmd: python ./data/random_data.py
    deps:
      - ./data/random_data.py
  preprocess_data:
    cmd: python ./data/prepare_data.py
    deps:
      - ./data/prepare_data.py
      - ./data/dummy_sensor_data.csv
  add_dummy_sensor_data:
    cmd: |
      dvc add ./data/dummy_sensor_data.csv
  add_train_data:
    cmd: |
      dvc add ./data/prepared/train.csv
  add_test_data:
    cmd: |
      dvc add ./data/prepared/test.csv
  monitor_performance:
    cmd: |
      python ./train/monitor.py
    deps:
      - ./train/monitor.py
      - ./data/prepared/train.csv
      - ./data/prepared/test.csv
  train_results:
    cmd: |
      dvc add ./train/model_regsistery
    deps:
      - ./train/model_regsistery
  push_data:
    cmd: |
      dvc push
