stages:
  pull_data:
    cmd: dvc pull
  add_data:
    cmd: python ./data/random_data.py
    deps:
      - ./data/random_data.py
  preprocess_data:
    cmd: python ./data/prepare_data.py
    deps:
      - ./data/prepare_data.py
      - ./data/dummy_sensor_data.csv
  add_dummy_sensor_data:
    cmd: |
      dvc add ./data/dummy_sensor_data.csv
  add_train_data:
    cmd: |
      dvc add ./data/prepared/train.csv
  add_test_data:
    cmd: |
      dvc add ./data/prepared/test.csv
  push_data:
    cmd: |
      dvc push
  train_model:
    cmd: python ./train/train.py
