name: MLOps Workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - i200469

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup DVC
      uses: iterative/setup-dvc@v1

    - name: Configure DVC remote
      run: |
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON_1 }}" > service_account.json
        dvc remote modify zahid gdrive_user_credentials_file ./service_account.json

    - name: Pull data from DVC remote
      run: |
        dvc pull
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag mlopsmystics:latest

    - name: Push Docker iamge
      run: |
          docker tag mlopsmystics:latest ${{ secrets.DOCKER_USERNAME }}/project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/project:latest
