name: MLOps Workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - i200469

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Pull data from Google Drive
      run: |
        dvc pull

    - name: Generate data
      run: |
        python ./data/random_data.py


    - name: Push data to Google Drive
      run: |
        dvc add ./data/dummy_sensor_data.csv
        dvc push
